### ISSUE TITLE
Wrong format of the requirements.txt

### ISSUE THREAD

**Issue by antonalekseev** [fbaptiste/pydantic-essentials#1]
Hello, Fred. It appears that the contents of the `requirements.txt` file is in the wrong format (as per https://pip.pypa.io/en/stable/reference/requirements-file-format/). You probably copied the correspondent `Pipfile` section and forgot to fix it. As far as no versions are pinned, the following will do.

```
jupyterlab
pydantic
email-validator
python-dateutil
pytz
requests
datamodel-code-generator
```

Thank you for the great content you have both on Udemy and YouTube.

**Comment by fbaptiste** [comment]
Hi,
Thanks for pointing that out - I did indeed just copy things from a Pipenv file and forgot to clean it up for a requirements file. Thanks for pointing that out! I will fix it.
